### ISSUE TITLE
WaveFuncTable

### ISSUE THREAD

**Issue by Lukas314** [flexible-atomic-code/fac#133]
Hello,
I haven't found a description in the manual of the functions output. The output are 9 tables!
Thank you

**Comment by mfgu** [comment]
the doc does need a major rework. unfortunately it might take a while.
just in case you need this specific piece, the 10 columns for a bound orbital in the WaveFuncTable output:
idx, r, v*r, u*r, p, q, pr, qr, ph, qh

idx, radial grid index
r, radius
v+u is the potential used to generate the one-electron radial wave functions.
p, q, the large and small components of the radial wave function.
pr, qr, the large and small components of the radial wavefunction, for a potential excluding the vaccum polarization terms.
ph, qh, the large and small components of the radial wave function for the hydrogen-like ion with finite nucleus size.
pr/qr, ph/qh are used for screened self energy estimation.

**Comment by jazspid** [comment]
The radius is in atomic unit, is that true?

**Comment by mfgu** [comment]
yes

**Comment by SimonG2** [comment]
Hello,

I have a question regarding the bound and continuum wavefunctions. 
Are these wavefunctions calculated for a particular fac.Config(' ') states? 
In brief, will these wavefunctions depends from the electronic configuration?

Thanks.
