### ISSUE TITLE
override compiler

### ISSUE THREAD

**Issue by mfgu** [flexible-atomic-code/fac#134]
the new setup.py no longer respects the CC env variables to override the c compiler. How can we specify a different compiler than the default used by python?

**Comment by fujiisoup** [comment]
`-ccompiler=icc` does not work?
I will try to send a fix, but I don't have icc compiler. 
I think I need your help later.

**Comment by fujiisoup** [comment]
Can you paste the output of `make pfac`?
I copied many part from Intel's repository, I think it is not so far from the icc support.

**Comment by mfgu** [comment]
in the previous version, if CC is not defined, the compiler used in the python extension is the one chosen by python distutil, which should be the one that was used to build python itself. 

with the new version, when i override with --ccompiler, the library flags for python is not automatically included, so extension build fails.

**Comment by mfgu** [comment]
not necessarily icc. the behavior we want is if CC is not defined, the extension modules should be built with the default compiler that python distutil chooses. but if CC is defined, that one should be used. e.g., in my system, the python default compiler does not support openmp, so i need to override it to compile the extensions. in the previous version, i just set the CC env, and pythons distutil pick it up automatically. with the new version, i can use the -ccompiler= but it drops the python lib link flags.

**Comment by mfgu** [comment]
looks like it's the -shared option you hard coded in the compiler setup that's causing the problem. it may work in linux, but not on mac.
the options should be from the python sysconfig setup, so that it's consistent with the platform.

**Comment by fujiisoup** [comment]
> the options should be from the python sysconfig setup, so that it's consistent with the platform.

Thanks for the investigation.
Can you update that part if you have a time?
(I do not have a mac.)

The testing server works on Linux, so you can see if the compile succeeds on linux.

**Comment by mfgu** [comment]
the test env needs to have pthread lib installed.

**Comment by fujiisoup** [comment]
Closed by #137
