### ISSUE TITLE
check failure

### ISSUE THREAD

**Issue by mfgu** [flexible-atomic-code/fac#138]
check still fails. it's comparing with an old copy of ref/* data. where is it getting those old data from?

**Comment by fujiisoup** [comment]
I am still working this.

I think it is better to compare the result with older data to make sure that our calculation is not drifting, unless we found a numerical bug in the previous result.
I will send a fix not comparing the long name but just values, in a few days (or a week).

**Comment by fujiisoup** [comment]
Closed via #140
