### ISSUE TITLE
Transition orders in .ce file changes in if openmp is enabled

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#17]
I added a validation test with openmp in #16 , and I noticed that the transition order changes if we switch on openmp.

e.g. in demo/excitation/ne.ce, we got 
without openmp, the transitions are orderd in the ascent manner
```
     0  0      1  4  7.2447E+02 1
-1.0000E+00  0.0000E+00  0.0000E+00
...
     0  0      2  2  7.2648E+02 1
 8.3122E-03 -6.1412E-03  9.4388E+04
...
     0  0      3  0  7.3714E+02 1
-1.0000E+00  0.0000E+00  0.0000E+00
```
but with openmp, it is randomly ordered
```
     0  0      1  4  7.2434E+02 1
-1.0000E+00  0.0000E+00  0.0000E+00
...
     0  0      3  0  7.3700E+02 1
-1.0000E+00  0.0000E+00  0.0000E+00
...
     0  0      4  2  7.3831E+02 1
 8.3792E-03 -6.1549E-03  9.4387E+04
```

My current test code does not take account the ordering, and it simply reports the results are different.
Is it an intended behavior?
If so, I will update the test code. 

But I personally think it would be better for users if the transition order is kept same independent from how many cores are used.

**Comment by mfgu** [comment]
openmp is intended for use in large calculations. the block of transitions may easily contain millions of transitions with GBs of data. We want to best performance, holding the transition records in memory and sort and write out in the end wastes cpu and memory that can be used more productively. for small problems we may add a sort when writting out to the ascii file.

**Comment by fujiisoup** [comment]
OK, thanks. I will revert my previous merge commite and update the test scrupt.
