### ISSUE TITLE
Radial Wave functions

### ISSUE THREAD

**Issue by Lukas314** [flexible-atomic-code/fac#188]
I am writing my master thesis at the moment using the flexible atomic code and there are some questions concerning the output of the radial wave functions of the bound and continuum states:

-)Continuum wave function: 
  Since the essential output of the continuum wave function at order 1keV was only a fraction of 1 Bohr radius, I changed 
 some values in the file "consts.h" in the directory "faclib" in the following way: 
--) I changed the values
#define MAXRP      3000  /* maximum radial mesh */
#define DMAXRP     1200  /* default radial mesh points */
#define GRIDASYMP  36    /* no. points in one wavelength near infinity */
to
#define MAXRP      3000  /* maximum radial mesh */
#define DMAXRP     2500  /* default radial mesh points */
#define GRIDASYMP  419    /* no. points in one wavelength near infinity */
Is there a reason why these values are chosen to be the ones in the file, because the output looks fine to me?
-) Ionization: (I wrote a sequence of the code at the end)
--)If I want calculate the continuum states, does the Config() should include the electron configuration before or after the ionisation process? 
--)Is there a main difference, if I use the function Closed() for the closed shells instead of Config() (?), because the function OptimizeRadial() only contains the groups I include in the argument as far as I understood?
--) Since in the manual it is written that one should NOT use the function OptimizeRadial() for levels bigger than n=4, does this has any influence on the WaveFuncTable() output?  
___________________________________________________________________________
Example: Ionization Xe-2p

fac.SetAtom('Xe')
fac.Config('1* 2', group='1s')
fac.Config('2* 2', group='2s')
fac.Config('2* 6', group='2p')
fac.Config('3* 2', group='3s')
fac.Config('3* 6', group='3p')
fac.Config('3* 10', group='3d')
fac.Closed('4s')
fac.Closed('4p')
fac.Closed('4d')
fac.Closed('5p')
fac.Closed('5s')
fac.ConfigEnergy(0)
fac.OptimizeRadial(['1s','2s','2p','3s','3p','3d'])
fac.ConfigEnergy(1)
fac.WaveFuncTable('FXe2pbd.txt', 2, -2)
fac.WaveFuncTable('FXe2p100.txt', 0, -2, 100)
_____________________________________________
Thank you very much in advance

**Comment by Lukas314** [comment]
Thank you very much for your quick reply. I am currently working with a theoretical framework to calculate ionization probabilities that needs 
 both the continuum wave function and the bound state wave function, thats why I need the range for the continuum wave function, where the bound state wave function asymptotically is zero. Sorry I should have mentioned that before.

Thank you very much now I understand the concept of the Closed() function, unfortunately I haven't found a description like that in the manual, so thank you very much in advance!

**Comment by SimonG2** [comment]
Sorry to open this 3 years old post. But I think something interested was asked and I'm looking for the same replies. 

How can I calculate the wavefunctions (bound and continuum) for a specific fac.Config state?
Futhermore, I also see as the OP was pointing out, that the continuum wavefunction is truncated at some fraction of the Bohr radius. 

<img width="530" alt="Screenshot 2021-04-29 at 21 18 19" src="https://user-images.githubusercontent.com/43409680/116606050-761bf480-a930-11eb-8ece-a49402de8e8b.png">
