### ISSUE TITLE
Continuous Deployment?

### ISSUE THREAD

**Issue by HPLegion** [flexible-atomic-code/fac#201]
Hi,

I have seen that you started using Travis and that the release source code packages have disappeared (the link in the readme is broken at least). Does this mean that you are switching over to a more continuous release model and I should download the source code directly from the repository for buliding fac in the future?

Also I saw that the python 3.6 builds are passing on Travis - does this mean fac is ready to be used with python 3 now?

Keep up the good work guys, cheers!

**Comment by mfgu** [comment]
yes, it should work with python 3, thanks to Keisuke.

and I would recommend using the most up to date version.

**Comment by HPLegion** [comment]
Cool stuff, thanks!
