### ISSUE TITLE
Unstable behavior for sorting ascii file when openmp is enabled

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#22]
I think by #21 , the ascii file is now sorted even when openmp is enabled.

But the new behavior looks somehow unstable.
The tests passed when the PR is sent, but failed after the merge commit.

In my local environment, 
```
cd demo/NeL
make openmp
```
**sometimes** fails and causes a segfault (but sometimes succeeds).
I guess it is failing when writing to the file?

**Comment by fujiisoup** [comment]
Note that we can use only one core in the automatic testing server. It might be worth also testing on the local machine.

**Comment by mfgu** [comment]
i don't seem to get this error regardless of number of threads used. can you help to pinpoint where the error is occurring?

**Comment by fujiisoup** [comment]
@mfgu 
But I became unable to reproduce this issue either in my environment and in the automatic testing server.
Something wrong happened at that moment...
I appreciate you for checking this issue in your environment.

Closing.

**Comment by fujiisoup** [comment]
I restarted the testing system and the issue was not reproduced.

I do not have time to investigate this today, but it could depend on the server condition, such as there are too many jobs...?
I reopened this issue.

**Comment by mfgu** [comment]
issue fixed in PR#27
