### ISSUE TITLE
How tout modify a code ?

### ISSUE THREAD

**Issue by meryembel** [flexible-atomic-code/fac#285]
Hi, 
I am PHD student and i'am working in EIE , one part of my work assigned to modified excitation programme (collision strength ) .
But i have problem , when i try to do a very small change  , the fac work normaly also when i deleted  excitation.c the fac work 
Could you help me please ?.

**Comment by mfgu** [comment]
did you recompile and reinstall after modification?

**Comment by meryembel** [comment]
No,i didn't .
But how can i do that , i was install pfac by
Make pfac and sudo python setup.py  install ?

**Comment by mfgu** [comment]
first make clean
then do the steps you would do as if it's a new install.

**Comment by meryembel** [comment]
Thank you , it change .
