### ISSUE TITLE
How to calculate energy level when l is large?

### ISSUE THREAD

**Issue by zhangyanning55** [flexible-atomic-code/fac#304]
Hi,

I am using FAC to calculate the energy level. When l is 20,  it works well. However, once l is more than 20, for example, l = 21, there is always the error 'Segmentation fault (core dumped)'. Is there any method to avoid such error?

The script is:
fac.SetAtom('Xe')
fac.Config('1s', group = 'i')
fac.Config('1s1 24[20]1', group = 'd')   #This works. But  fac.Config('1s1 24[21]1', group = 'd') will make mistake.

fac.SetBreit(-1)
fac.ConfigEnergy(0)
fac.OptimizeRadial(['i'])
fac.ConfigEnergy(1)
fac.Structure('Xe.lev.b', [ 'd'])
fac.MemENTable('Xe.lev.b')
fac.PrintTable('Xe.lev.b', 'Xe.lev', 1)

**Comment by mfgu** [comment]
add this line at the top of the script
SetHydrogenicNL(24,23,24,23)
the 4 args are n, l, n, l. make them larger for higher n/l orbitals.

**Comment by zhangyanning55** [comment]
Thanks so much!
Now it works!
