### ISSUE TITLE
OptimizeRadial does not update `a`

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#31]
I noticed that `OptimizeRadial` does not update `a`, and thus `a==0` is always used.
I checked both wih `GetPotential` and `SavePotential` functions.

Is it an intended behavior?
From the manual, it looks that both `lambda` and `a` should be updated.

The parameterized potential that is used in FAC is
![image](https://user-images.githubusercontent.com/6815844/38925763-860e1f2a-433b-11e8-9a59-a6b59c9be843.png)

**Comment by mfgu** [comment]
it was supposed to be another parameter to improve the potential. but later
found to be unnecessary.

**Comment by fujiisoup** [comment]
Thanks.
Ok, then it is a documentation issue.

I will send a PR to update the manual in a few days.

**Comment by fujiisoup** [comment]
Closed via #32
