### ISSUE TITLE
crm depends on the order of `structure` executed

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#313]
Results of cr model change depending on the order of `Structure` executed.

For the example shown below, the calculated spectral energies and intensities are

|energy|strength for first example|strength for the second example|
|---------|---------|---------|
|0.035638 |1.417296e-04|2.131977e-04|
|8.904886 |3.859020e+05|5.766114e+05|
|8.941247 |2.152486e+05|5.698960e+04|
|8.905609 |4.282408e+04|1.133818e+04|
|7.90035  |2.848635e+04|7.910924e+04|
|7.864712 |5.712235e+04|1.586341e+05|

They show a significant difference.
`.en`, `.tr` files look (effectively) the same.

The following is an example script that generates the above result
```
SetAtom('Si')
Closed('1s')
Closed('2s')
Closed('2p')

Config('lev1', '3s2 3p1')
Config('lev2', '3s2 3d1')
Config('lev3', '3s2 4s1')

ConfigEnergy(0)
OptimizeRadial(['lev1'])
ConfigEnergy(1)

Structure('text2.en',['lev1','lev2'])  # line 1
Structure('text2.en',['lev3'])  # line 2
MemENTable('text2.en')

TransitionTable('text2.tr', ['lev1', 'lev2', 'lev3'], ['lev1', 'lev2', 'lev3'])
CETable('text2.ce', ['lev1'], ['lev1', 'lev2', 'lev3'])
```
```
AddIon(13,1,text2)
SetBlocks(-1)
SetEleDist(0, 1000, -1, -1)
SetTRRates(0)
SetCERates(1)
SetAbund(13, 1.0)
SetEleDensity(1000)
InitBlocks()
SetIteration(1e-4, 0.5)
LevelPopulation()
SpecTable('text2.sp',0)
```

For example 2, we interchanged line 1 and line 2 and kept the rest same.

**Comment by mfgu** [comment]
fixed the issue. 
although it's recommended that the ground state of the ion to be in the first block of levels.

**Comment by fujiisoup** [comment]
Thank you a lot!
