### ISSUE TITLE
OpenMP and MPI confusion

### ISSUE THREAD

**Issue by jongrumer** [flexible-atomic-code/fac#337]
Dear all,

Just wanted to highlight that there seems to be an overall confusion in the code, readme's etc. when referring to the type of parallelization - in a few instances I've come across, OpenMP (shared memory multiprocessing) is used to explain what's really implemented in MPI (message passing interface). Like this bit in the main readme:

> 2-4. Parallel computation
Some of the functions have a parallel version using MPI. You can build with MPI enabled using the option --with-mpi=***, where *** is the MPI implementation installed on your machine. It has been tested with lammpi and openmp. If you are using openmp, specify --with-mpi=omp.

where OpenMP and MPI is clearly mixed up. Or in codes such as `mpiutil.c`

```C
178 void ResetWidMPI(void) {
179 #if USE_MPI == 2
180   if (!MPIReady()) {
181     printf("openmp not initialized\n");
182     Abort(1);
183   }
184 #endif
```
where openmp is given in the error message, while it's actually MPI that is tested?

This is a classic confusion for all of us I guess, since the most common implementation of MPI is called `open-mpi`. The code seems to use both MPI (open-mpi) and OpenMP, which is really good of course for HPC computations if used correctly (OpenMP for local machine vecorization and MPI for node communication). I guess the important bit to understand is wether `InitializeMPI()` defines no. of OpenMP threads or MPI processes? It seems to be the latter.

Maybe this doesn't matter too much, and I'm sure you're aware of it :) Just thought it deserved to be mentioned as I was a bit confused there for a while. 

Thanks for a good job, looking forward to test the code out! Cheers!
*Jon Grumer*
*The CompAS collaboration (grasp, atsp etc)*
*Theoretical Astrophysics, Uppsala University*

**Comment by mfgu** [comment]
Hi Jon,
I originally implemented some parallelization with MPI, mostly in the MBPT method. but it quickly become clear that using MPI requires a large memory footprint as each process is independent. almost all of the parallelization in FAC is now implemented with OpenMP. However, the setup and initialization of openmp share some of the functions with MPI, which predates the addition of OpenMP support. e.g. in configure script, --with-mpi=omp instructs the compiler to include OpenMP support. InitializeMPI(n) means initialize OpenMP with n threads. I did not implement the simultaneous use of MPI and OpenMP, in fact, I pretty much gave up MPI by now.

**Comment by jongrumer** [comment]
@mfgu 
Thank you for your response - went on vacation and missed it :)

And thank you for explaining the dev progress, things are clearer now. I get a lot of memory seg faults during parallel computations, but I just noticed that this might be related to the comment you've added in the main readme on that the execution isn't thread safe, and that one should stick to a single run per python kernel. I will try that as I mostly run multiple runs simultaneously. 

Cheers,
Jon

**Comment by Fowfow** [comment]
Thanks for the thread, I was confused too :)
