### ISSUE TITLE
perturbed hamiltonian

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#347]
By setting `ip=1` in `Structure(fn, [, hfn ], g [, p [, ip ] ])`, fac ignores the non-diagonal element within p.

But how does it compute the eigenvalues from the perturbed hamiltonian?
I computed the eigenvalues from the hamiltonian but I found if `ip=0`, the eigenvalues of the output hamiltonian (computed by the direct eigenvalue decomposition) is consistent with the energy level in `.en` file in 1e-10 eV order level (the ionization energy is ~3000 eV), 
but if `ip==1`, the eigenvalues from the perturbed hamiltonian are different from those in .en file in the order of 0.01 eV.

![image](https://user-images.githubusercontent.com/6815844/61182408-e14ce780-a632-11e9-891c-4149c48dccae.png)

Here is the script I tested
```
SetAtom('W')
Closed('1s')
Closed('2s')
Closed('2p')

Config('g1_0', '3s2 3p4')
Config('g1_2', '3s2 3p3 3d1')
Config('g1_3', '3s2 3p3 4s1')
Config('g1_4', '3s2 3p3 4p1')
Config('g1_5', '3s2 3p3 4d1')

# configuration to be considered as a perturbation
Config('g2', '3s1 3p4 4p1')

ConfigEnergy(0)
OptimizeRadial('g1_0')
ConfigEnergy(1)

Structure('test_W.en', 'test_W.ham', ['g1_0', 'g1_2', 'g1_3', 'g1_4', 'g1_5'], ['g2'], 1)
# for full hamiltonian
# Structure('test_W.en', 'test_W.ham', ['g1_0', 'g1_2', 'g1_3', 'g1_4', 'g1_5'], ['g2'])  
```

**Comment by fujiisoup** [comment]
And it looks that the eigen decomposition of the perturbed Hamiltonian is closer to the .en output with the full hamiltonian than .en output withh the perturbed Hamiltonian.

![image](https://user-images.githubusercontent.com/6815844/61182607-376f5a00-a636-11e9-89f5-d5a1d0cc0c88.png)

**Comment by mfgu** [comment]
with Structure(...., [g], [p]) is equivalent to Structure(...., [g], [p], 0)

if ip=0, the full hamilton of all states in g and p groups are  used. after
diagonalizing, the states belong to the p group is then discarded. so in
this mode, you would expect the energy levels to be the same as the result
from Structure(...., [g,p]) for levels that belong to the g group.

if ip=1, the off diagonal elements from the p subspace is ignored, the
hamilton is then reduced to an effective hamilton with only states from the
g group, and the interactions with p group are included as perturbation.
you would expect some difference for the energies as compared with the full
hamilton case.

**Comment by fujiisoup** [comment]
Thanks, @mfgu .

I think I understand correctly.
My problem is that 
the two energies
1. energies in .en file (with `ip=1` computation)
2. eigenvalues computed outside of FAC with the FAC's Hamiltonian with ip=1 mode.

are different.

They are the same if `ip=0` is used (for both .en file and hamiltonian)
Does fac make further approximation if ip=1 mode, addition to ignoring the nondiagonal within p?

**Comment by mfgu** [comment]
Yes. The diagonalization method is approximate. See doc/papers/structure.ps

**Comment by fujiisoup** [comment]
That makes sense. Thanks.
