### ISSUE TITLE
TR_RECORD changes if multipole is specified in `TransitionTable`

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#36]
I noticed that if we specify multipole (`m`) in `TransitionTable` (even I set the default value -1), the value of `strength` in the binary file changes.
The ascii file does not change with or without multipole argument.

I suppose there were some updates in the binary file format?
Here is the relevant page of the document.

![image](https://user-images.githubusercontent.com/6815844/39032591-2543cff4-44a9-11e8-9505-432a67c3b7c7.png)
![image](https://user-images.githubusercontent.com/6815844/39032598-2b5303ba-44a9-11e8-8532-14db2913dc43.png)

**Comment by fujiisoup** [comment]
It looks that the default multipole of `TransitionTable` is 0 (not -1 as written in the doc), and in that case the oscillator strength *gf* is saved in the binary file. In other cases *M* values are saved.

Is it correct? If so, I would like to update the doc.

**Comment by mfgu** [comment]
default is 0, which sums up all multipoles for the rate.
