### ISSUE TITLE
Help with the The RT RECORD output

### ISSUE THREAD

**Issue by jongrumer** [flexible-atomic-code/fac#390]
Hi all,

Feel bad for asking this, but really tried to work things out myself and feel I don't get much further without a lot of effort. Could I please ask someone to clarify the current table output from the various RECORD's for me, the RT RECORD  in particular.

I'm trying to learn how to dig out the various level in- and out-flows of a CRM-model, limited to say electron collision excitation/de-excitation and radiative decays. The RT record seems helpful here but can't make sense of the table produced by RateTable(). 

Take the [NeL demo case](https://github.com/flexible-atomic-code/fac/blob/master/demo/NeL/ref/Ne03a.rt) as an example:

```
              NB          TR          CE          RR          AI          CI
     0    0   1.0000E+00  2.0000E+00  0.0000E+00  3.0000E+00  1.0000E+00 -1.0000E+00 1*2.2*1
     1    1   8.2916E-08  2.0000E+00  1.5998E+01  3.0000E+00  1.0000E+00 -1.0000E+00 1*2.2*1
     2    2   1.5890E-07  4.0000E+00  1.6198E+01  3.0000E+00  1.0000E+00 -1.0000E+00 1*2.2*1
     3    3   3.0589E-11  2.0000E+00  1.3631E+02  3.0000E+00  1.0000E+00 -1.0000E+00 1*2.3*1
     4    4   5.6260E-12  2.0000E+00  1.4073E+02  3.0000E+00  1.0000E+00 -1.0000E+00 1*2.3*1

```
In column order: 
* *dir* should give the direction (0:in, 1:out)) of the transition but seems to be just level index?
* *iblock* should be index of the superlevel block from which the rates originate?
* *NB* gives level populations - correct?
* *TR* should be total rad trans rates - but seems to give 2J+1?
* *CE* should be col exc rates - but seems to give the excitation energy?
* *RR* should be rad rec/photoionization rates - but seems to give the number of electrons?
* *AI* should be autoionization rates - gives 1?
* *CI* should be col ionization - gives -1?
* *icomplex* is correct I guess?

I guess AI and CI could be 1 and -1 to show that these contributions are not included. 

I have a similar issue, although not as severe, with understanding other RECORDS and HEADERS fully, most notably the SP record, but let's start with RT.

I know that the manual is outdated, and I'm a total FAC noob learning, but these outputs just seems to be way to off?

Even a short answer would be much appreciated :) Maybe @fujiisoup knows?

All the best,
Jon

**Comment by mfgu** [comment]
Hi Jon
The RateTable output is a bit complicated. In the NeL example, those
numbers are not rates at all. there are different modes for this function
that output different things. I wrote this function early in the days. I no
longer recommend using it. to see detailed. rate. flows in and out of
levels, it's better to use the DumpRates() function. the doc on this
function should be good.

the SP_RECORD, on the other hand, is the main output of the crm. the doc on
this should be still valid.

**Comment by jongrumer** [comment]
Great, thanks a lot! And thanks for the rapid response. I'll use DumpRates instead then! And good to know I can trust the SP doc.

Have a good day,
Jon
