### ISSUE TITLE
Related to mix mode calculation (UTA(0) and (1))

### ISSUE THREAD

**Issue by pritivish** [flexible-atomic-code/fac#403]
Hello All,
I am trying to do a mix mode calculation which is done in a new release. 
I am giving UTA(0) for few groups and UTA(1) for few groups. But it is taking only the UTA type which I have given later. please suggest me weather mix mode is possible in 1.1.5 latest release.

**Comment by mfgu** [comment]
no, mixing uta and non-uta is not supported.

**Comment by pritivish** [comment]
okay, Thank you so much for the response. Actually I was reading a paper by **M. Poirier ( https://doi.org/10.1002/ctpp.201700070)** where it is mentioned that he has done some calculations using FAC and obtained some results with the mixed mode recently developed. that is why I thought it is supported in this version.
