### ISSUE TITLE
unit in .en file

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#424]
Hi @mfgu 

Did you change the unit of the values in .en (binary) file?
Values changed depending on the version of `fac` by a factor of 1e28.

**Comment by mfgu** [comment]
maybe you just need to rebuild FAC from scratch after make clean.

**Comment by fujiisoup** [comment]
Thank you for your advice.
Yes, it was my environmental problem.
Fixed. Thanks.
