### ISSUE TITLE
segfault & bus error, and mismatched population in CRM involving multiple ions

### ISSUE THREAD

**Issue by bio-tonic** [flexible-atomic-code/fac#455]
version: **FAC 1.1.5**

Hello, developer：

I have some problems when I calculated a spectral model involving more than one ion using function `spectrum()`. In fact, the ions with k electrons and k-1 electrons are introduced by `AddIon()` and `SetBlock()` respectively. 
NormalizeMode was set to 2. 
EN, CE, TR, CI, RR, AI data of _ion k_ and EN, CE, TR data of _ion k-1_ has already calculated. 

1. segfault & bus error
However, if the CE data of  _ion k-1_ is larger than hundreds of KBs (maybe 500K), errors occur when `SetCERates()` is called, mainly segfault and sometimes bus error. 
 I find that the segfault in `SetBlock()` has been fixed last year. I'm not sure whether that was just the BUG I encountered.

2. mismatched population data in different parts  
2.1 two ions
To avoid the segfualt or bus error, I reduced the number of the configurations involved in CE.  Though the code run successfully, new problem occurred. For an example:
EN data of _ion k_ :
```
NELE    = 68
NLEV    = 3192
...
NELE    = 67
NLEV    = 493 
 ILEV  IBASE    ENERGY       P   VNL   2J
  3192     -1  1.19279240E+02 1   501    7 4*31.5*8                         4f13                                             4f+7(7)7
  3193     -1  1.21438905E+02 1   501    5 4*31.5*8                         4f13                                             4f-5(5)5
...
  3673     -1  2.24462514E+02 1   503    5 4*31.5*8                    4f13.5p5.5f1                                     4f-5(5)5.5p-1(1)4.5f+1(7)5
...

```
And EN data of _ion k-1_
```
NELE    = 67
NLEV    = 493
  ILEV  IBASE    ENERGY       P   VNL   2J
     0     -1  0.00000000E+00 1   501    7 4*31.5*8                         4f13                                             4f+7(7)7
     1     -1  2.15966489E+00 1   501    5 4*31.5*8                         4f13                                             4f-5(5)5
...
    481     -1  1.05183273E+02 1   503    5 4*31.5*8                    4f13.5p5.5f1                                     4f-5(5)5.5p-1(1)4.5f+1(7)5
...
```
After CRM, part of SP data is followed:
```
#population
NELE    = 67
NTRANS  = 1
TYPE    = 0000000
IBLK    = 0
ICOMP   = 4*31.5*8
FBLK    = 0
FCOMP   =
  3192      0  1.192792E+02  9.8041E-01  8.0000E+00  1.5485E-03
...
  3193      0  1.214389E+02  8.0384E-12  6.0000E+00  4.0073E+07

...
  3672     19  2.240807E+02  1.7817E-13  4.0000E+00  1.2970E+08
  3673     20  2.244625E+02  3.9569E-05  6.0000E+00  9.7364E+01
  3674     21  2.247520E+02  0.0000E+00  1.2000E+01  0.0000E+00

#line emissivity TR
NELE    = 67
NTRANS  = 3
TYPE    = 0000505
IBLK    = 138
ICOMP   = 4*31.5*8
FBLK    = 5
FCOMP   = 4*31.5*8
     1      0  2.159665E+00  3.2163E-03  8.1284E+01  9.7364E+01
#population = 3.9569E-05.

#line emissivity RR
NELE    = 68
NTRANS  = 1
TYPE    = 0000005
IBLK    = 1
ICOMP   = 4*31.5*8
FBLK    = 190
FCOMP   = 4*31.5*9
3193     50  4.350177E+01  8.1631E-24  1.0155E-12  4.0073E+07
#population = 8.0385E-12
```

According to the population part, the population of level 3193 belonging to _ion k-1_ should be **8.0384E-12**(It’s too small. It should be comparable to 3192). But the **TR** 3193→3192 (1→0) in line emissivity part suggested that its population  is 3.2163E-03/ 8.1284E +01 = **3.9569E-05** which was the population of level 3673 (3673’s population shouldn’t be so large, I think.). It's not a coincidence since the population is still matched level 3673 when I chose different temperature, though there might be a very little deviation. But the matched level would change if base data was different. And I checked some other levels of _ion k-1_, they all had such phenomenon. 
However, the population calculated from the **RR** 3193→50 is **8.0385E-12**. It was equal to the population part. 
**If I reduced the total number of levels of _ion k-1_ , the problem could be avoided.** But no more than about 200~300 levels...

2.2 three ions 
The numbers of levels and CE transitions of _ion k-1_ are limited. But the _ion k-1_, w7+, is my interested ion. I modified k from 68 to 67. Therefore, _ion k_ → _ion k+1_, _ion k-1_ → _ion k_. They are both introduced by `AddIon()`. And another ion, _ion k-1_, that is w8+, was introduced by `SetBlock()`. Therefore, more CE transitions of W7+ were allowed. However, except the error happened on _ion k-1_, new problem occurred again. It's opposite to the former one. The population calculated from **RR** process between _ion k_ and _ion k+1_ matched the wrong level of _ion k_. But the **TR** process was right.

```
NELE	= 67                                                     
NTRANS	= 1                                                    
TYPE	= 0000000                                                
IBLK	= 65                                                     
ICOMP	= 4*31.5*8                                               
FBLK	= 0                                                      
FCOMP	=                                                        
     0      0  1.192792E+02  5.0628E-01  8.0000E+00  2.4123E+02
…
     1      0  1.214389E+02  1.1523E-01  6.0000E+00  3.2322E+02
…
     5      0  1.616404E+02  2.3321E-07  8.0000E+00  6.5483E+06
#lev0: 4f13   lev5: 4f13.5p5.5d1

NELE	= 68                                                     
NTRANS	= 2416                                                 
TYPE	= 0000005                                                
IBLK	= 70                                                     
ICOMP	= 4*31.5*8                                               
FBLK	= 853                                                    
FCOMP	= 4*31.5*9                                               
3192    640  2.915478E+00  1.3869E-18  5.9468E-12  6.5483E+06
#population = 2.3322E-07
```

This phenomenon can’t be repeated in the demo script involving Fe23+, Fe22+, Fe21+(NELE=3, 4, 5). But I can’t avoid that in my own script even if I reduced the levels of _ion k_ in the EN data of _ion k+1_ to only 5. And the matching result in that case is shown below. 
```
     level number in the transition         level number whose (direct) population equals to the  calculated population 
                    3192 (0)               →                              6
                    3193 (1)               →                              5
                    3194 (2)               →                              0
                    3195 (3)               →                              1
                    3196 (4)               →                              7
```

There're different phenomenon in different situations. I'm not sure whether there're also similar phenomenon in CE, CI, AI processes since we can't see that intuitively. 

3. NormalizeMode
By the way, does the norm_mode=2 mean that the total population is fixed to the total number set by `SetAbund()` and the populations of different ions can be compared? And I can't understand the result when m=3. What's the meaning when m=3?

**Comment by bio-tonic** [comment]
I dump the data in one test involving 3 ions. k=67. It looks clearer.
`DumpRates(fn, 67, 0 ,-1, 1):`
```
67      0     30      0  7   -1  501 -1.61161047E+04  6.730E-01  1.203E+01  1.000E+00
...
```

`DumpRates(fn, 68, 0 ,-1, 1):`
```
...
67   3403     35      0  7   -1  501 -1.61161047E+04  2.584E-08  6.548E+06  1.000E+00
...
67   4192     30      0  7   -1  502 -1.61124411E+04  6.730E-01  1.203E+01  1.000E+00
...
```
level 0 in the first table and level 3403 in the second table should be the same energy level 4f13. Their energies are the same. However, their populations and decay rates are different.
level 4192 is 4f13.5s1.5d1 and Its energy is higher But its population and decay rate equal to level 0's data.

**Comment by mfgu** [comment]
Can you attach all scripts that generate the atomic data and the spectrum, so that I can recreate these problems

**Comment by bio-tonic** [comment]
Mr. Gu:


&nbsp; Thank you, Mr. Gu. Here are my scripts in one of my test, and part of results. FAC version is 1.1.5. In this test, I meet the problem 2.2.&nbsp;
&nbsp; In script "68d.py", the parameter 'k' should be modified to 66, 67 and 68 to gain the data of w8+, w7+ and w6+, respectively. Therefore, the scripts "68d.py" should be run for 3 times totally. Then the scipt "ysptest.py" should be run for once.&nbsp;


Best wishes
Yan
2020/08/03


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flexible-atomic-code/fac"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 凌晨5:15
收件人:&nbsp;"flexible-atomic-code/fac"<fac@noreply.github.com&gt;;
抄送:&nbsp;"肺功能"<956007383@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [flexible-atomic-code/fac] segfault &amp; bus error, and mismatched population in CRM involving multiple ions (#455)





 Can you attach all scripts that generate the atomic data and the spectrum, so that I can recreate these problems
 
 &gt; On Aug 2, 2020, at 5:08 PM, bio-tonic <notifications@github.com&gt; wrote:
 &gt; 
 &gt; ﻿
 &gt; I dump the data in one test involving 3 ions. k=67. It looks clearer.
 &gt; DumpRates(fn, 67, 0 ,-1, 1):
 &gt; 
 &gt; 67      0     30      0  7   -1  501 -1.61161047E+04  6.730E-01  1.203E+01  1.000E+00
 &gt; ...
 &gt; DumpRates(fn, 68, 0 ,-1, 1):
 &gt; 
 &gt; ...
 &gt; 67   3403     35      0  7   -1  501 -1.61161047E+04  2.584E-08  6.548E+06  1.000E+00
 &gt; ...
 &gt; 67   4192     30      0  7   -1  502 -1.61124411E+04  6.730E-01  1.203E+01  1.000E+00
 &gt; ...
 &gt; level 0 in the first table and level 3403 in the second table should be the same energy level 4f13. Their energies are the same. However, their populations and decay rates are different.
 &gt; level 4192 is 4f13.5s1.5d1 and Its energy is higher But its population and decay rate equal to level 0's data.
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bio-tonic** [comment]
The FAC I used seems to be earlier than 2019.05. And, though all the CX data could be read successfully, only the first ion's CX data could be involved in the CRM calculation.
Considering a lot of fix during the last year, I install the lastest version in a vmware workstation. **However**, 
If NormalizeMode=2, the model i used above would fail.
```
Population Iteration:
    0  1.0000E+00  1.1271E-01  1.1271E-01  3.0101E+08
    1        -NAN  1.0728E-01  2.1998E-01  3.0101E+08
```
If NormalizeMode=1, though the model runs successfully, the result is wrong. There's no process between different ions, i.e, CI, AI and RR process. And the coresponding dump file is empty. 
But the demo FeL goes well. I don't know what's wrong.

**Comment by bio-tonic** [comment]
As I mentioned, the latest version would return segfault, I did some test after installing the old version (around 05.2019).
The problem seems to be caused by function `FindLevelBlock()`. 
`crm.c` `SetBlocks()`
```
#1026  	  r1 = (EN_RECORD *) malloc(sizeof(EN_RECORD)*h.nlevels);
          nlevels = FindLevelBlock(h.nlevels, r0, r1, ion->nele-1, ifn); 
          printf("r0[0].ilev=%d \t r1[0].ilev=%d \n",r0[0].ilev,r1[0].ilev); 
```
It returned:
```
r0[0].ilev=1514	r1[0].ilev=0
# Matching correctly

r0[0].ilev=3192	r1[0].ilev=5
# Matching incorrectly
```
The function `FindLevelBlock()` is very long. I modified `SetBlocks()` instead. Since **the levels were in the same order in 2 EN data files**, the code was modified like below:
```
	  r1 = (EN_RECORD *) malloc(sizeof(EN_RECORD)*h.nlevels);
	  nlevels = FindLevelBlock(h.nlevels, r0, r1, ion->nele-1, ifn);
	  *r1=*r0;
	  for (int xx=0;xx<h.nlevels;xx++){
	      r1[xx].ilev=xx;
	      }
```
The result seemed to be right. Both the `.sp` file and dump file. But I was not sure whether it was reliable even the levels were in the same order in 2 EN data files. After all, I haven't understood the the subsequent codes in this function yet.
[fac-master_20190501.zip](https://github.com/flexible-atomic-code/fac/files/5089167/fac-master_20190501.zip)

**Comment by mfgu** [comment]
I'm finally having some time to check on this. But I cannot find your scripts that you said you attached.

**Comment by bio-tonic** [comment]
I have tried to fix the problem. 
The first one is the segfault. In line 5890, `crm.c`, the subscript should be `jb`, not `ib`, or the script would return segfault if the data block is larger than NRTB. I find that this has been fixed days ago. #463 

The second one is the mismatched population. It happens in the function `FindLevelBlock`. But my version is before 2019.05. This function changed a lot after several updates. Debug on old version fisrt. 
1. OLD VERSION
```
  if (k < n) {
    FSEEK(f, sfh, SEEK_SET);
    nr = ReadENHeader(f, &h, swp);
    j = h.nlevels;
    for (i = 0; i < h.nlevels; i++) {
      nr = ReadENRecord(f, &r1[k], swp);
      if (strcmp(r1[k].ncomplex, r0[0].ncomplex) != 0) j--;
      if (j < n) {
	k++;
	if (k == n) break;
      }
    }
  }

  if (k != n) return k;
```
 The conditional statement `if (j < n)` doesn't limit enough since `j =  h.nlevels` and `n = h.nlevels` in my scripts. Once a level whose complex is different from the 'ground' level's comes, `j` will smaller than `n`. Then all the levels coming later will be imported. Since some levels whose complex are the same as the 'ground' level's have been imported before this code, part of the data to be sorted may be duplicate. This causes the mismatching. 
So I modified a little like below. It works well, though it looks rough and redundant. In my script, each ion is optimized before calculating the level table. So the levels can be matched relatively good according to their level indexs. 
Therefore, I don't think it is universally applicable. Some relativistic configurations whose energy are high may mismatch. 
```
  if (k < n) {
    FSEEK(f, sfh, SEEK_SET);
    nr = ReadENHeader(f, &h, swp);
    j = h.nlevels;
    for (i = 0; i < h.nlevels; i++) {
      nr = ReadENRecord(f, &r1[k], swp);
      if (strcmp(r1[k].ncomplex, r0[0].ncomplex) != 0) {
      j--;
      if (j < n) {
	k++;
	if (k == n) break;
      }
      }
    }
  }
```
2. NEW VERSION
In fact i can't understand the new function `FindLevelBlock`. Anyway, i try the new one for my script. The result is rather strange. I am sorry that I don't take much effort on the new code, so i can't ensure the accuracy of description. Here are the new problem. 

 level 3121~3123 are missing
```
NELE    = 67
NTRANS  = 1
TYPE    = 0000000
IBLK    = 1
ICOMP   = 4*31.5*8
FBLK    = 0
FCOMP   =
  3120      0  1.214322E+02  5.8814E-02  6.0000E+00  1.7743E+02

NELE    = 67
NTRANS  = 1
TYPE    = 0000000
IBLK    = 2
ICOMP   = 4*31.5*8
FBLK    = 0
FCOMP   =
  3124      0  1.616338E+02  1.1538E-07  8.0000E+00  6.8607E+06


```
 one level has different population
```
NELE    = 67
NTRANS  = 1
TYPE    = 0000505
IBLK    = 2
ICOMP   = 4*31.5*8
FBLK    = 0
FCOMP   = 4*31.5*8
     5      0  4.236129E+01  7.8772E-01  6.8606E+06  5.2315E+01

NELE    = 67
NTRANS  = 1
TYPE    = 0000505
IBLK    = 2
ICOMP   = 4*31.5*8
FBLK    = 1
FCOMP   = 4*31.5*8
     5      1  4.020158E+01  3.8439E-03  6.8607E+06  5.3086E+01
```

**Comment by bio-tonic** [comment]
Mr. Gu:


&nbsp; Thank you, Mr. Gu. Here are my scripts in one of my test, and part of results. FAC version is 1.1.5.&nbsp;
&nbsp; In script "68d.py", the parameter 'k' should be modified to 66, 67 and 68 to gain the data of w8+, w7+ and w6+, respectively. Therefore, the scripts "68d.py" should be run for 3 times totally. Then the scipt "ysptest.py" should be run for once.


Best wishes
Yan
2020/09/24






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flexible-atomic-code/fac"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月20日(星期天) 下午5:11
收件人:&nbsp;"flexible-atomic-code/fac"<fac@noreply.github.com&gt;;
抄送:&nbsp;"肺功能"<956007383@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [flexible-atomic-code/fac] segfault &amp; bus error, and mismatched population in CRM involving multiple ions (#455)





 
I'm finally having some time to check on this. But I cannot find your scripts that you said you attached.

**Comment by mfgu** [comment]
the level mismatch is due to the assumption I made that the levels in the same block have the same distribution over the principal quantum numbers, or the n-complexes as I had called them. I have now relaxed  this restriction. try the new version  to see if it fixes your problem.

**Comment by bio-tonic** [comment]
almost there. In a 2-ions model, level's population is the same as the result of the modified old code. So is the light emissivity. But the TR rates seem to be strange. While the data in dump files are the  same despite that there's more information with the new code. 
`version around 2019.05`
```
#.sp file
NELE	= 67
NTRANS	= 1
TYPE	= 0000505
IBLK	= 5
ICOMP	= 4*31.5*8
FBLK	= 0
FCOMP	= 4*31.5*8
     5      0  4.236129E+01  7.7388E-01  6.8273E+06  6.8607E+06
...
     5      1  4.020158E+01  3.7763E-03  3.3315E+04  6.8607E+06

#.d0 file
 67   3124      5      0  7   -1  502 -1.61145467E+04 1.1335E-07 6.8607E+06 1.0000E+00

#.d1 file
 3124    3119  6.827E+06  0.000E+00
 3124    3120  3.332E+04  0.000E+00
```




`the lastest version` 
```
NELE    = 67
NTRANS  = 1
TYPE    = 0000505
IBLK    = 5
ICOMP   = 4*31.5*8
FBLK    = 0
FCOMP   = 4*31.5*8
     5      0  4.236129E+01  7.7388E-01  6.8606E+06  6.4688E+01
...
     5      1  4.020158E+01  3.7763E-03  6.8607E+06  6.4730E+01

#.d0 file
 67   3124      5      0  7   -1  502 -1.61145467E+04 1.1335E-07 6.8607E+06 1.0000E+00 6.8606E+06 3.8042E+01

#.d1 file
 68    3124    3119  6.827E+06  0.000E+00
 68    3124    3120  3.332E+04  0.000E+00
```
