### ISSUE TITLE
2 mistakes in function SetCXRates()

### ISSUE THREAD

**Issue by bio-tonic** [flexible-atomic-code/fac#456]
I want to involve CX process `SetCXRates(2,'N2')` into my model #455 . But I meet 2 error.
1. I calculated the model in a server. But when I dump the CX rates, I found the number of transitions was much smaller than the original CX data. 
```
NELE    = 68
NTRANS  = 733676
TGTS    = N2
```
But according to the dump file, there were only 32767 transitions were involved.
` 32767,4      底端`

And I tried again in VMware+ubuntu, then it returned segfault. 
I checked the code. When m=2:
file `crm.c`
```
#5531     for (nb = 0; nb < fh.nblocks; nb++) {
#5532    	n = ReadCXHeader(f, &xh, swp);
...
#5549         for (i = 0; i < xh.ntransitions; i++) {
#5550    	      n = ReadCXRecord(f, &xr[jb++], swp, &xh);
...
#5583             for (jb = 0; jb < nrb; jb++) {
#5584     	              AddRate(ion, ion->cx_rates, &rts[jb], 0, irb);
#5585             }
#5586             nrb = h.ntransitions-i-1;
#5587             nrb = Min(nrb, NRTB);
```
CX data is stored in the struct variable `xh`. However, when reseting `nrb`, the code uses the variable `h`.
I didn't know why the results of the mistake were different in the serve and VMware. 
I fixed that in my VMware. At least it run successfully and the number of transitions was right. But  since I didn't have root of the serve, I was not clear what would happen in the serve if I modified the code.

2. Only one ion's CX data could be imported. I had the CX data of W8+→W7+ and W7+→W6+.They were stored in 2 files. W8+ was introduced by `SetBlocks`. The latter one were read unsuccessfully. 
```
	    if (xh.nele==68) printf("%d\n",nrb);
	    nrb = Min(nrb, NRTB);
	    jb = 0;
# nothing is printed onto the screen
```
Then only W8+→W7+ was involved in the model. And the dump file for CX W7+→W6+ was empty. If I deleted the former data, the latter one was involved in the model successfully.

**Comment by bio-tonic** [comment]
The reason of problem 2 have been found.

In code `crm.c`
```
#5381     for (k = 0; k < ions->dim; k++) {
#5382         ion = (ION *) ArrayGet(ions, k);
...
#5525         if (m == 2) {
...
#5570		    for (k = 0; k < xh.ne0; k++) {
#5571		          if (cx->rcx[k] <= 0) {
#5572		            cx->rcx[k] = -500.0;
#5573	        	  } else {
#5574	    	        cx->rcx[k] = log(cx->rcx[k]);
#5575	    	      }
#5576	            }
...
```
The loop variables of main loop and sub loop are both `k`. When the sub loop is finished, k  is no longer the order of the ions, and ends the main loop. Therefore, the CRM can't import another ion.

**Comment by mfgu** [comment]
the two issues have been fixed. Thanks.
