### ISSUE TITLE
Importing configs and wavefunctions to other scripts?

### ISSUE THREAD

**Issue by StevenBromley** [flexible-atomic-code/fac#457]
Hello,

I am trying to do large-scale structure calculations for levels and transitions with FAC. Ideally, once the structure is as good as I can get it, I would like to calculate transition rates. Because the calculations are so large, it would be beneficial to break these calculations into pieces. However, if I simply import the .en file, I lose all information on the wavefunctions and the configuration group labels assigned in the Config() calls. Is it possible to save this information, or somehow import it after I have verified the structure is good, from a file(s) into another script that will generate transition rates or electron impact cross sections? This way it is not necessary to spend a large amount of time recalculating the structure before calculating rates or cross sections using those wavefunctions. 

EDIT: I want to clarify. I am asking if it possible to save the wavefunctions and configuration group labels so that a user can import them into other scripts that would be used to generate transition rates or electron impact cross sections. For example, if my structure script runs close to the max walltime of the available computing resources it would be best if a separate script could then handle calculating transition rates of subsets of levels, that way the whole structure calculation need not be rerun to calculate other properties. Is it possible to somehow save the wavefunction information and re-load it? Also, is there any way to recover the original configuration group labels, or perhaps re-assign them correctly in other scripts that would import this information?

Thanks,
Steve

**Comment by jazspid** [comment]
I guess fac.WavefuncTable can help you save the wavefunctions. I don't know how to save group label, though. Sorry.

**Comment by StevenBromley** [comment]
Hi Jazspid,

Thank you for this insight. I can save individual wavefunctions with WavefuncTable(). Alternatively, one can use the BasisTable() to save the mixing coefficients; I've been using that to look at the LS labels after converting from jj to LS coupling with the GRASP jj2lsj module. However, at the moment it doesn't seem possible to reload the wavefunctions back into FAC. If it is not possible, it would be a helpful addition to FACs capabilities in future releases.
