### ISSUE TITLE
Missing Configurations in .en file?

### ISSUE THREAD

**Issue by StevenBromley** [flexible-atomic-code/fac#471]
Hello all,

I am trying to calculate the structure of neutral through ~doubly ionized elements such as gold/platinum. I have noticed that when running a very small calculation w/ little to no CI included, I get the correct number of levels in the .en file. However. when running larger amounts of CI, the number of levels for some configurations in the .en file is reduced. For example, the doubly excited configuration of Pt I, 5d8 6s 6p, should have 90 levels. However, when running a large CI calculation, I get ~75 levels in 5d8 6s 6p.
. 

Similarly, the configuration 5d9 7s has 4 levels, but 5d9 8s only outputs 3 levels. Is there a flag or command somewhere to print all levels explicitly, or is this a problem deeper in the code related to the CI treatment?

Best wishes,
Steve Bromley

**Comment by mfgu** [comment]
Steve,
configuration is not a good quantum number. when you have CI mixing, the
level is labeled by the configuration of the leading component. when there
is strong interaction, this label becomes largely meaningless. a level
originally from one configuration may end up being labeled with another.
you should see the total number of levels for a given symmetry is the same
as the sum of all interacting configurations, but how these levels are
partitioned between different configs depends on the detail of mixing.

**Comment by StevenBromley** [comment]
Hello,

Thank you for the quick response. I used jj2lsj to convert to LS coupling to look at the components, and indeed the missing 8s level is mixed heavily into 5d9 7d. The same is true for one of the 6s levels, which mixes heavily with 5d8 6s2. I suppose this means the 'missing' 6s6p levels are listed under one of the other configurations, most likely 6s2 6p. 

Thanks & best wishes,
Steve Bromley
