### ISSUE TITLE
What Units Are Used in .cx output file from CXTable?

### ISSUE THREAD

**Issue by rhmatti** [flexible-atomic-code/fac#484]
I have been trying to incorporate charge exchange cross section calculations to my existing script, and have managed to get what I think is proper output for them. However, I cannot find anywhere in the documentation what units the values are given in. I would typically assume the energies are given in eV, and the cross sections are given in cm^2. However, a colleague of mine has already determined that the .sp binary files give the energies in Hartrees by looking at the source code, so I was hoping someone could confirm the units that are used in the .cx output files from the CXTable function. I have attached one such file to this post for reference (I have changed the file extension from .cx to .txt so that I could upload it to github).
[Ne9.txt](https://github.com/flexible-atomic-code/fac/files/6313638/Ne9.txt)

Best regards,
Rick

**Comment by mfgu** [comment]
all FAC binary output are in atomic units. in the ascii output files, the energies are in eV, cross sections are in 10^-20 cm2

**Comment by rhmatti** [comment]
I see. Thank you very much for the clarification.

Best regards,
Rick
