### ISSUE TITLE
a preliminary bug fix : lost TR & CE rates for the ion0 when more than 2 ions are involved in CRM

### ISSUE THREAD

**Issue by bio-tonic** [flexible-atomic-code/fac#508]
Hello, developer.
Thought the result of CRM in old version FAC (2019) is self-consistent, it imports data and calculates too slow. And the OpenBlas doesn't work on the old FAC. The new FAC (2020) is used to get fast CRM. The result of 2-ions CRM in new FAC is nearly the same as that in old one. But when more than 2 ions are involved in CRM, the result is different. After checked the dumped data, I found that the TR & CE rates data for the ion0 (which had the least electrons) are lost in file **dump.1** and file **dump.3**. And also, the rates in file **dump.0** is wrong. The sum of rates (CX+CI+AI+RR) of each level of ion0 is nearly 0, CE&TR rates are just 0. Therefore, the CE&TR datas were not improted in CRM if  more than 2 ions.
Part of file `dump.0 `in 2-ions CRM. ion0 's NELE=67
```
 68   9908   5491     32  8   -1  603 -1.61145940E+04 2.3905E-26 1.4646E+14 2.1052E-03 1.4646E+14 2.5008E-01
 68   9909   5491     33  2   -1  603 -1.61144870E+04 5.9004E-29 2.9749E+14 5.1963E-06 2.9749E+14 6.2390E-01
 67   9910      0      0  7   -1  501 -1.61159986E+04 2.0247E-01 3.6423E+03 1.0000E+00 0.0000E+00 3.6423E+03
 67   9911      1      0  3   -1  501 -1.61159283E+04 1.2476E-01 7.0411E+02 1.0000E+00 1.5975E-02 7.0410E+02
 67   9912      2      0  5   -1  501 -1.61159157E+04 6.3075E-02 3.7401E+03 1.0000E+00 9.2681E+01 3.6474E+03
```
Part of file `dump.0` in 3-ions CRM. ion0's NELE=67
```
 68   9908   5495     32  8   -1  603 -1.61145940E+04 3.9895E-25 1.4646E+14 1.5033E-03 1.4646E+14 2.5044E-01
 68   9909   5495     33  2   -1  603 -1.61144870E+04 1.4603E-27 2.9749E+14 5.5027E-06 2.9749E+14 6.2427E-01
 67   9910     74      5  7   -1  501 -1.61159986E+04 5.8453E-01 1.7312E-01 1.0000E+00 0.0000E+00 6.4762E-03
 67   9911    103      0  3   -1  501 -1.61159283E+04 1.5799E-01 1.9729E-01 1.0000E+00 0.0000E+00 1.2446E-03
 67   9912     86      7  5   -1  501 -1.61159157E+04 2.4540E-01 1.7320E-01 1.0000E+00 0.0000E+00 6.5013E-03
```

The reason of BUG was found in `SetBlocks()` 
```
 #976       for (k = 0; k < ions->dim; k++) {
               ...
#1035          n0 = 0;
               ...
#1044          for (nb = 0; nb < fh.nblocks; nb++) {
                   n = ReadENHeader(f, &h, swp);
                   if (h.nele == ion->nele) {
	               FSEEK(f, h.length, SEEK_CUR);
	               continue;
#1049              } else if (h.nele == ion->nele-1) {    
                       ...
#1115                  if (k > 0) {... 
#1138                  }else {   
#1228                      n0++;...
#1234                  }       
#1235	               ion0.nionized = n0;
#1242              }
#1251          }   
#1451      }
```      
The parament `n0` is reset to 0 each next k. If there're more than 2 ions, ion->dim>1.  When k=1 or larger, the loop which makes `n0++` is not available. Then `ion0.nionized = n0 = 0`. So the datas can't be imported in `SetTRRates()` and `SetCERate()`.
After exchanging line `#1234` and line `#1235`, code `ion0.nionized = n0;` is not available when k>0. Then the result of CRM is the same with the old one. 
It's a simple fix. Maybe other bugs will occur. I wish developer can check for it.

**Comment by mfgu** [comment]
good find. I will fix this. although if you are  not supposed to trust in the spectral model from ion0. the level structure in ion0 is  limited, mainly to provide targets for ionization processes. so if you want spectra from ion0, it's better to include it explicitly in the list of ions
