### ISSUE TITLE
CETable outputs 0ABS(ETA) EXCEEDS 1000 on large configurations

### ISSUE THREAD

**Issue by hbekker** [flexible-atomic-code/fac#509]
Dear Ming Feng,

The following configuration
```
fac.SetAtom('Th')
fac.Closed('1s', '2s', '2p', '3s', '3p', '3d', '4s', '4p', '4d') 

fac.Config('n1', '4f9')
fac.Config('n2', '4f8 5s1')
```

gives " 0ABS(ETA) EXCEEDS 1000" when running CETable (on 'n1' to 'n2' if I remember correctly). Is there anything that can be done about this issue?

Thanks,
Hendrik

**Comment by mfgu** [comment]
Hi hendrik,
this message is largely harmless. its due to some transitions having very
small excitation energy. the coulomb bethe approximation for high partial
waves has problems numerically. the calculations then switch to plane wave
born approximation in such cases.

**Comment by hbekker** [comment]
Thank you. I have left the script running this time and indeed it seems to have completed without issues.
