### ISSUE TITLE
Documentation for Get Potential

### ISSUE THREAD

**Issue by StevenBromley** [flexible-atomic-code/fac#518]
Hello,

I am trying to look at the radial potential before/after using OptimizeRadial. I used GetPotential() in the pfac interface to save the potential to file, and I am seeing 18 columns. It is clear that columns 0 and 1 are the radial grid index and value, with the 3rd column as Z(r). The manual states that 8 columns should be present:

i, r, Z(r), V (r), Vd(r), Ve(r), Ve′(r), and U(r)

The output file from GetPotential() prints 18 columns, the last four of which are 0 at each grid point. The potential of interest V(r) (the optimized potential according to documentation) should be in column 3 but is 0 at each grid point.

Is the documentation still correct, or is there some error in GetPotential not printing correctly?

Best wishes,
Steve Bromley

**Comment by mfgu** [comment]
the potential is (c5+c6)/r, where c5 and c6 are the 5th and 6th columns, counting from 1.

**Comment by StevenBromley** [comment]
Thank you for the response. I think I have found what I need. Going ahead and closing this ticket.
