### ISSUE TITLE
make check error in demo folder on ubuntu

### ISSUE THREAD

**Issue by zezhong-zhang** [flexible-atomic-code/fac#524]
As following the compiling instructions, I compiled both sfac and pfac successfully on Linux (Ubuntu-20.04) with
```
./configure --with-mpi=omp
make
sudo make install
make pfac
make install-pfac
```

when `make` the `demo/` folder examples:
```
make[1]: Entering directory '/home/zzhang/code/fac/demo/structure'
make[1]: Leaving directory '/home/zzhang/code/fac/demo/structure'
make[1]: Entering directory '/home/zzhang/code/fac/demo/excitation'
make[1]: Leaving directory '/home/zzhang/code/fac/demo/excitation'
make[1]: Entering directory '/home/zzhang/code/fac/demo/pirr'
make[1]: Leaving directory '/home/zzhang/code/fac/demo/pirr'
make[1]: Entering directory '/home/zzhang/code/fac/demo/aidr'
make[1]: Leaving directory '/home/zzhang/code/fac/demo/aidr'
make[1]: Entering directory '/home/zzhang/code/fac/demo/ionization'
make[1]: Leaving directory '/home/zzhang/code/fac/demo/ionization'
make[1]: Entering directory '/home/zzhang/code/fac/demo/polariz'
  0  0.0000E+00  1.00000000E+00  0.00000000E+00  2.3127E-05
  1  0.0000E+00  1.00000000E+00  0.00000000E+00  2.1935E-05
make[1]: Leaving directory '/home/zzhang/code/fac/demo/polariz'
make[1]: Entering directory '/home/zzhang/code/fac/demo/NeL'
TR: g2 -> g2
TR: g2 -> g3
TR: g2 -> g4
TR: g2 -> g5
TR: g3 -> g3
TR: g3 -> g4
TR: g3 -> g5
TR: g4 -> g4
TR: g4 -> g5
TR: g5 -> g5
CE: g2 -> g2
CE: g2 -> g3
CE: g2 -> g4
CE: g2 -> g5
Population Iteration:
    0  1.0000E+00  2.4080E-05  2.4080E-05  2.4994E+07
    1  3.0018E-03  3.6955E-05  6.1035E-05  2.4994E+07
    2  4.2764E-05  2.5988E-05  8.7023E-05  2.4994E+07
    3  2.1387E-05  4.3154E-05  1.3018E-04  2.4994E+07
    4  1.0696E-05  1.0967E-05  1.4114E-04  2.4994E+07
    5  5.3489E-06  2.7895E-05  1.6904E-04  2.4994E+07
    6  2.6750E-06  2.4080E-05  1.9312E-04  2.4994E+07
    7  1.3378E-06  2.5988E-05  2.1911E-04  2.4994E+07
    8  6.6905E-07  4.0054E-05  2.5916E-04  2.4994E+07
make[1]: Leaving directory '/home/zzhang/code/fac/demo/NeL'
make[1]: Entering directory '/home/zzhang/code/fac/demo/tests'
running crm_OI.py
Population Iteration:
    0  1.0000E+00  2.5034E-05  2.5034E-05  2.5002E+07
    1  0.0000E+00  5.1975E-05  7.7009E-05  2.5002E+07
make[1]: Leaving directory '/home/zzhang/code/fac/demo/tests'
```

But when test the code with `make check`, it has the following error:

```
make[1]: Entering directory '/home/zzhang/code/fac/demo/structure'
ne.lev
ne.tr
 Tests passed!
make[1]: Leaving directory '/home/zzhang/code/fac/demo/structure'
make[1]: Entering directory '/home/zzhang/code/fac/demo/excitation'
ne.ce
ne.ceM
ne.lev
 Tests passed!
make[1]: Leaving directory '/home/zzhang/code/fac/demo/excitation'
make[1]: Entering directory '/home/zzhang/code/fac/demo/pirr'
li.lev
li.rr
 Tests passed!
make[1]: Leaving directory '/home/zzhang/code/fac/demo/pirr'
make[1]: Entering directory '/home/zzhang/code/fac/demo/aidr'
se.ai
Traceback (most recent call last):
  File "/home/zzhang/code/fac/demo/aidr/../check.py", line 263, in <module>
    check(args[1], args[2])
  File "/home/zzhang/code/fac/demo/aidr/../check.py", line 230, in check
    check_ai(actual_file, expected_file)
  File "/home/zzhang/code/fac/demo/aidr/../check.py", line 115, in check_ai
    _check_block(actual_blocks, expected_blocks,
  File "/home/zzhang/code/fac/demo/aidr/../check.py", line 49, in _check_block
    _raise(i, key, actual, expected)
  File "/home/zzhang/code/fac/demo/aidr/../check.py", line 35, in _raise
    raise ValueError(message)
ValueError: Large difference is found in block 0 key free_2J. The largest abs difference is in (0,) with 1 vs 3  The largest rel difference is in (0,) with 1 vs 3 
make[1]: *** [../Make.common:10: check] Error 1
make[1]: Leaving directory '/home/zzhang/code/fac/demo/aidr'
make: *** [Makefile:13: check] Error 1
```

Also I don't know whether it is due to the same error, but when I call pfac in python to calculate the bonded state, it behaves all right. However, when I calculate for continuum state for an atom with one core electron removed, it kills the python kernel with the following error:
```
Max iteration before finding correct nodes in RadialBound a: 2 2 233 3 -1 -2.33248e-154
Rank=0, Error occured in RadialSolver, -2
Rank=0, 3 -1 -4.699E-01
```
would  appreciate if you can give some suggestions!

**Comment by mfgu** [comment]
let's just leave the this issue open. 

but I cannot reproduce your error in either Mac or Linux. I tried on Ubuntu and Debian, and both seem to be ok. can you double check if it's these statements that lead to the error?

**Comment by mfgu** [comment]
I see the problem now. you are running the two parts sequentially in the same script. You cannot run OptimizeRadial twice with different configurations in the same script. if you want to do that, after the first part, you need to re-initialize the radial package using pfac.fac.ReinitRadial(0)
but normally, if you want to have atomic states from two neighboring ions in the same script, and calculate processes that connect them, they must be generated with the the same potential from a single OptimizeRadial. that does mean that the potential is not quite optimal for one of the ions. But this is necessary as the method used in FAC relied on the fact that all radial wavefunctions are calculated from the same local potential.

**Comment by zezhong-zhang** [comment]
Yes, indeed that was the problem for the error message. With `pfac.fac.ReinitRadial(0)` to re-initialise the radial package, the code can run. Many thanks @mfgu!

Regarding the potential, I want to calculate the (bounded and continuum) radial wave function for both atom and ion of that atom (with same Z) but with one core electron taken away. I am still bit unclear about the generated the same potential from a single OptimizeRadial ... as I think the potential of ion should be different from that of atom. Thus shouldn't I initialise the potential with the corresponding orbital configurations?

**Comment by mfgu** [comment]
if you only need energy levels of both ions, then you should use different potentials, as that's more accurate. but if you are trying to calculate ionization, Auger processes between the two ions, then a single potential must be used, as the method used relies on the orthogonal property of the radial wavefunctions. the energy levels of one ion will of course be less accurate. but FAC is designed to work for highly charged ions, so this is generally not an issue.  when using it for neutrals, that is a general limitation.

**Comment by zezhong-zhang** [comment]
I see, many thanks for the explanation @mfgu! I will close the issue now.
