### ISSUE TITLE
Error occurred in RadialSolver -99

### ISSUE THREAD

**Issue by AtsushiTanimoto** [flexible-atomic-code/fac#537]
Thank you for maintaining the flexible-atomic-code.
If we ran the following code, we would get the following error.
How do we solve this problem?

Code:
pfac.atom.atomic_data(nele=[2], asym="B", dir=directory)

Error:
An error occurred in RadialSolver -99

**Comment by mfgu** [comment]
this has been fixed.

**Comment by AtsushiTanimoto** [comment]
Thank you for your quick response.
