### ISSUE TITLE
Output wavefunction of explicit spin-orbital splitting 

### ISSUE THREAD

**Issue by zezhong-zhang** [flexible-atomic-code/fac#563]
Hi @mfgu , 

I am wondering if it is possible to output wavefunction for the explicit spin-orbital? For instance, in the non-relativistic picture, for 2p orbital with spin up/down has a J=L+S= 3/2 or 1/2 with occupancy of 2/3 and 1/3, it will yield to different energies and radial wavefunctions. 

When calculate the potential with ` fac.OptimizeRadial`, it make sense to use the mean configuration. But when calculate the wavefunction with `WaveFuncTable(fn, n, k [, e ])`, spin up/down should give different results. Does it require a fundamental change of the code?

**Comment by zezhong-zhang** [comment]
The relativistic quantum number already encodes the spin information, with k = -s(2*j+1). Thus, my apologies for the silly question above. Using the following minimum examples, I can output the spin up and down wave functions for both the bounded and continuum states. 

However I noticed that I cannot input l' = 0 for spin down continuum state, otherwise the python will crash. The spin up in contrast is doing fine. I would really appreciate your suggestions @mfgu 

```python
import pfac.fac

Z=14
epsilon = 1
def kappa(l,s):
    return int(-s*(2*(l+s)+1))

config = "1s2 2s2 2p6 3s2 3p2"
configstring = pfac.fac.ATOMICSYMBOL[Z] 
pfac.fac.SetAtom(pfac.fac.ATOMICSYMBOL[Z])
# Set up configuration
pfac.fac.Config(configstring, config)
# Optimize atomic energy levels
pfac.fac.ConfigEnergy(0)
# Optimize radial wave functions
pfac.fac.OptimizeRadial(configstring)
# Optimize energy levels
pfac.fac.ConfigEnergy(1)
pfac.fac.WaveFuncTable('Bounded_spin_down.txt', 2, kappa(1,-1/2)) # the calculation is fine
pfac.fac.WaveFuncTable('Bounded_spin_up.txt', 2, kappa(0,1/2)) # the calculation is fine
pfac.fac.WaveFuncTable('Continuum_spin_up.xtx', 0, kappa(0,1/2), epsilon) # the calculation is fine
pfac.fac.WaveFuncTable('Continuum_spin_down.txt', 0, kappa(1,-1/2), epsilon) # the calculation is fine
pfac.fac.WaveFuncTable('Continuum_spin_down.txt', 0, kappa(0,-1/2), epsilon) # the calculation is crashed
```

**Comment by mfgu** [comment]
the radial wavefunctions do not depend on projections of spin or orbital angular momenta. it only depends on l and j in the Dirac equation for a spherical potential. when l=0, you have only one possibility of j=1/2. when l > 0, you have two cases with j=l+1/2 and j=l-1/2.

**Comment by zezhong-zhang** [comment]
I see, many thanks @mfgu. Just to clarify, in the case that the bounded state has spin -1/2, when excited to continuum state with l=0, even though the spin should not be flipped during the transition, there is only one j= 0+s =1/2 as the wavefunction is interdependent of spin for s state?

**Comment by mfgu** [comment]
the z-components of spin or any angular momentum do not enter the radial wavefunctions. it only depends on the total value of the orbital and total angular momenta, l and j. kappa is dependent on the values of l and j, not the spin projections on any direction.

**Comment by zezhong-zhang** [comment]
Thanks @mfgu, I understand now.
