### ISSUE TITLE
The value of the population data is NAN

### ISSUE THREAD

**Issue by AtsushiTanimoto** [flexible-atomic-code/fac#566]
Thank you for maintaining the flexible atomic code.
We are trying to compute the population data using pfac.spm.spectrum.
If we ran the following code, the value of the population data would be NAN.
Why does this situation occur? How can we avoid this situation?

Code:
```
import numpy
import pfac.atom
import pfac.fac
import pfac.spm
import subprocess


if __name__=="__main__":
    atomic_number   = 9
    atomic_symbol   = pfac.fac.ATOMICSYMBOL[9]
    electron_number = 3
    densities       = 1e-10*numpy.logspace(10, 0, 1)
    temperatures    = 1e+00*numpy.logspace( 0, 0, 1)
    populations     = len(temperatures)*[(1+atomic_number)*[1.0]]
    indir           = "{0:s}/".format(atomic_symbol)
    outdir          = "{0:s}/{0:s}{1:02d}_spec/".format(atomic_symbol, electron_number)

    subprocess.run("mkdir {0:s}".format(indir), shell=True)
    subprocess.run("mkdir {0:s}".format(outdir), shell=True)
    pfac.atom.atomic_data(nele=range(electron_number-1,electron_number+1), asym=atomic_symbol, dir=indir)
    pfac.spm.spectrum(neles=[electron_number], temp=temperatures, den=densities, population=populations, pref=atomic_symbol, dir0=indir, dir1=outdir, nion=2, ai=0, ce=1, ci=1, rr=1, rrc=1)
```

Best regards,
Atsushi Tanimoto

**Comment by mfgu** [comment]
1 eV temperature is likely too low to excitation much. but more importantly
you need to include autoionization in the models, with ai=1.

**Comment by AtsushiTanimoto** [comment]
Thank you for your quick response.

> you need to include autoionization in the models, with ai=1.

Thank you for your suggestion. We have considered autoionization.
However, the value of the population data was still NAN.

> 1 eV temperature is likely too low to excitation much. 

After all, the low temperature was also a problem.
If we changed the temperature to 10 eV, we could successfully calculate the population data.

Many thanks,
Atsushi Tanimoto
