### ISSUE TITLE
problems compiling

### ISSUE THREAD

**Issue by kdere** [flexible-atomic-code/fac#604]
I have been trying to compile with gfortran-7 and gfortran-12 on a linux system and neither work

the most recent error is:

Warning: Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE with label 70 at (1)
coulcc.f:237:10:

  237 |       F = CF1R(X,ETA,ZLL,ACC8,SF ,RK,  ETANE0,LIMIT,ERR,NFP,
      |          1
Error: Type mismatch in argument ‘x’ at (1); passed COMPLEX(8) to REAL(8)
coulcc.f:237:10:

  237 |       F = CF1R(X,ETA,ZLL,ACC8,SF ,RK,  ETANE0,LIMIT,ERR,NFP,
      |          1
Error: Type mismatch in argument ‘eta’ at (1); passed COMPLEX(8) to REAL(8)
coulcc.f:237:10:

  237 |       F = CF1R(X,ETA,ZLL,ACC8,SF ,RK,  ETANE0,LIMIT,ERR,NFP,
      |          1
Error: Type mismatch in argument ‘zl’ at (1); passed COMPLEX(8) to REAL(8)
make[1]: *** [Makefile:15: coulcc.o] Error 1
make[1]: Leaving directory '/home/ken/Downloads/python/fac-1.1.4/coul'
make: *** [Makefile:25: lib] Error 2

hope this make some sense

Ken Dere

**Comment by mfgu** [comment]
Hi Ken,
I have fixed this issue in recent updates. it's because the newer version of gfortran is more strict on the argument types.

**Comment by kdere** [comment]
I tried with the lastest 1.1.4 release and that did not work.  I forked the current github files and made my own release and that did not work either.  Is it a question of the version of gfortran that I am using?

**Comment by mfgu** [comment]
what error messages do you get with the up to date version? it shouldn't be the argument type mismatch.

**Comment by kdere** [comment]
using the latest version of FAC and gfortran-12 I get

make[1]: Entering directory '/home/ken/Downloads/python/fac-1.1.5/toms'
gfortran -c -fPIC -O2 fdi.f
fdi.f:1055:33:

 1055 |       DATA RMACH(5) / Z'3E9A209B' /
      |                                 1
Error: BOZ literal constant near (1) cannot be assigned to a REAL variable [see ‘-fno-allow-invalid-boz’]
fdi.f:1054:33:

 1054 |       DATA RMACH(4) / Z'34000000' /
      |                                 1
Error: BOZ literal constant near (1) cannot be assigned to a REAL variable [see ‘-fno-allow-invalid-boz’]
fdi.f:1053:33:

 1053 |       DATA RMACH(3) / Z'33800000' /
      |                                 1
Error: BOZ literal constant near (1) cannot be assigned to a REAL variable [see ‘-fno-allow-invalid-boz’]
fdi.f:1052:33:

 1052 |       DATA RMACH(2) / Z'7F7FFFFF' /
      |                                 1
Error: BOZ literal constant near (1) cannot be assigned to a REAL variable [see ‘-fno-allow-invalid-boz’]
fdi.f:1051:33:

 1051 |       DATA RMACH(1) / Z'00800000' /
      |                                 1
Error: BOZ literal constant near (1) cannot be assigned to a REAL variable [see ‘-fno-allow-invalid-boz’]
make[1]: *** [Makefile:15: fdi.o] Error 1
make[1]: Leaving directory '/home/ken/Downloads/python/fac-1.1.5/toms'
make: *** [Makefile:29: lib] Error 2

**Comment by kdere** [comment]
I look through toms/fdi.f and the comments indicate that this part of the code is for an HP 730

**Comment by Zstar95** [comment]
> I look through toms/fdi.f and the comments indicate that this part of the code is for an HP 730

Using "-fallow-invalid-boz" option for FFLAGS/FFLAGSNO flag should be working.

**Comment by kdere** [comment]
Where do I specify "-fallow-invalid-boz"?

**Comment by mfgu** [comment]
the easiest way is to set env variable before configure. e.g., if using bash
export F77='gfortran -fallow-invalid-boz'

I will fix the code in a later update.

**Comment by Zstar95** [comment]
> Where do I specify "-fallow-invalid-boz"?

At present, in file 'Configure, find the lines 'FFLAGSNO="$FFLAGS"' and 'FFLAGS="$FFLAGS $fopt"', adding into the option "-fallow-invalid-boz" may work. Or you can use the way suggested by Prof. Gu.

**Comment by kdere** [comment]
I could not get those two suggestions to work.  But I went into toms/fdi.f and commented out the RMACH lines and then it would compile.

**Comment by mfgu** [comment]
this is fixed in the latest update.
