### ISSUE TITLE
"enlarge norbmap2" error during collisional excitation

### ISSUE THREAD

**Issue by DrRyanC** [flexible-atomic-code/fac#674]
Hello. 

While trying to calculate collisional excitation, FAC keeps returning the following error:

"too many free orbitals, enlarge norbmap2: 5000 >= 5000"

I have been unable to find any reference to an "norbmap2" parameter in the manual. 

Furthermore, it appears I can temporarily bypass this by decreasing the size of the user CEGrid for some charge states. However, this error still appears when defining as little as 4 grid points. 

Any help would be greatly appreciated!

**Comment by mfgu** [comment]
can you try the latest master branch, not the released 1.4 version?

**Comment by DrRyanC** [comment]
That did the trick. Thank you, Ming.
