### ISSUE TITLE
Possible issue with continuum wave for certain kappa

### ISSUE THREAD

**Issue by zezhong-zhang** [flexible-atomic-code/fac#684]
I have been using the continuum waves to calculate spectra for a while. I noticed that in certain combination of element and kappa, the continuum wave seems to be in a strange shape, which leads to an unexpected peak in the calculated spectrum. Interestingly the other kappa values seems to be fine,  here is an example:

```python
fac.SetAtom('Ba')
fac.Config('Ba_ex', '1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s2')
fac.ReinitRadial(0)
fac.ConfigEnergy(0)
fac.OptimizeRadial('Ba_ex')
fac.ConfigEnergy(1)
fac.WaveFuncTable('Ba_cwave.txt', 0, -4, 0.21)
fac.Reinit(config=1)
```
wave functions that I think looks wrong:
![image](https://github.com/flexible-atomic-code/fac/assets/13212584/f7353805-23cd-4de0-bc60-39f75e598e24)
wave functions that I think looks normal (all other kappa !=-4 also looks fine):
![image](https://github.com/flexible-atomic-code/fac/assets/13212584/74e9358a-54d3-4415-9e3f-8c589630d672)
@mfgu, would really appreciate if you could give some advice!

**Comment by mfgu** [comment]
for this particular case, the potential (including centrifugal term) has a local maximum at about r=3.0 for kappa=3 and -4, or L=3. the potential at the maximum is about V(r)=0.2 which creates a barrier. as the free electron energy become close to this value, it can get trapped inside the maximum, creating a temporary bound state. it's a well known physical effect, that shows up as resonances in the scattering cross sections.

**Comment by zezhong-zhang** [comment]
Many thanks @mfgu, this is indeed very interesting bound state in the continuum phenomenon (wiki https://en.wikipedia.org/wiki/Bound_state_in_the_continuum). I will close this issue.
