### ISSUE TITLE
Select python version on installation

### ISSUE THREAD

**Issue by aridaibordon** [flexible-atomic-code/fac#689]
Currently FAC detects the default Python installation and install pfac in the corresponding default site-packaged dir. Is there any way to force the installation in a different python version?

**Comment by mfgu** [comment]
before you run ./configure, set the env variable
export PYTHON=...
to the python executable of your choice. then run configure and make.

**Comment by aridaybordon** [comment]
It works perfectly. I think it should be included in the installation documentation as an additional comment under the "Install Python interface" section. At least in my case, it has caused more problems than it should. If you consider it worthy, I can open a pull request myself.

Thanks for your outstanding work!

**Comment by mfgu** [comment]
doc updated.
