### ISSUE TITLE
Complete subshell configuration string in atomic levels output file

### ISSUE THREAD

**Issue by Fowfow** [flexible-atomic-code/fac#691]
Hello,

Here is an example of an energy level where many subshells of the same principal quantum number (n=4 here) are closed.

Is it possible to activate an option for FAC to print not only "4d1.4f1" but the complete configuration string with all the closed subshells ?
For this example, it would be "4s2.4p6.4d1.4f1".
This is needed for postprocessing purposes where the complete subshell string is needed.

Can `fac.SetOption('dbase:remove_closed',0)` be useful ?

Best regards,

Fowler

Example :

`  ILEV  IBASE    ENERGY       P   VNL   2J`
`     0     -1  0.00000000E+00 1   403    8 4*10                             4d1.4f1                                          4d-1(3)3.4f-1(5)8`

**Comment by Fowfow** [comment]
I tried `fac.SetOption('dbase:remove_closed',0)` before `fac.SetAtom('Fe')` but it does not seem to work.


I managed to find another way to get the complete string I am looking for, by calling :
`new_n_occupation, new_nl_occupation, new_term =
 fac.FillClosedShell(nele, n_occupation, nb_occupation, term)`


where `nele`, `n_occupation` and `nl_occupation` come from the output file `ne.lev`
and `new_nl_occupation` is the complete string I am looking for.

**Comment by mfgu** [comment]
that is one way to get around. the other way is use
fac.SetOption('structure:full_name', 1) 
at the begining of the input script, this forces the energy level files to use full configuration label.
