### ISSUE TITLE
Query related to R-matrix data

### ISSUE THREAD

**Issue by atpchris** [flexible-atomic-code/fac#701]
Hi,
I have a question about calculating collision strengths using the R-matrix method. I have noticed that the collision strengths do not converge with the DW data at electron energies 10-20 times the threshold/excitation energy. I have already tried increasing both the number of partial waves and the radial basis functions per partial wave, but the results remain unchanged. Could you please clarify if there are any inherent limitations in the R-matrix calculations similar to those mentioned in the FAC manual for EIE data using the DW method? Specifically, the manual states: "Due to the limited radial grid size, collision strengths at energies significantly higher than the excitation energy (more than a few hundred times higher) are unlikely to be reliable."

Thanks

**Comment by mfgu** [comment]
R-Matrix method would have a hard time converging at such high energies. the maximum partial wave needed is likely in the hundreds, if not thousands, and there can be numerical problems dealing with such large angular momenta. The DW method will switch to PWB approximation at high energies, so you should use DW with default setting dealing with high energies.
