### ISSUE TITLE
Energy Level Differences with * Notation

### ISSUE THREAD

**Issue by GramajoAna** [flexible-atomic-code/fac#707]
Dear community,

I am currently learning to use FAC, and as part of the process, I have been calculating the energy levels of a specific atom. However, I noticed that the values in the output file differ substantially when using the * notation instead of the explicit 
angular momentum symbol for the possible configurations. Could someone explain why this happens?

Thank you for your help!

Best regards,
Ana
[file.txt](https://github.com/user-attachments/files/16995605/file.txt)

**Comment by fnevgeny** [comment]
In the first variant, you doubly count '3d10 4s2' (it's also a subset of 'n2').

**Comment by GramajoAna** [comment]
> In the first variant, you doubly count '3d10 4s2' (it's also a subset of 'n2').

Thanks for the quick  answer! I see, so the correct way to calculate the energy levels would be by specifying the angular momentum symbol? My concern also lies in the fact that these energy level values differ from those published in the NIST database for Zn I.

**Comment by fnevgeny** [comment]
> Thanks for the quick answer! I see, so the correct way to calculate the energy levels would be by specifying the angular momentum symbol?

You can do either way in principle; just don't put duplicate levels in the Hamiltonian (`Structure(...)`). Ideally, FAC should detect such a misusage and exit with an error.

> My concern also lies in the fact that these energy level values differ from those published in the NIST database for Zn I.

You shouldn't expect spectroscopy accuracy for multi-electron neutral or nearly neutral species.

**Comment by GramajoAna** [comment]
> > Thanks for the quick answer! I see, so the correct way to calculate the energy levels would be by specifying the angular momentum symbol?
> 
> You can do either way in principle; just don't put duplicate levels in the Hamiltonian (`Structure(...)`). Ideally, FAC should detect such a misusage and exit with an error.
> 
> > My concern also lies in the fact that these energy level values differ from those published in the NIST database for Zn I.
> 
> You shouldn't expect spectroscopy accuracy for multi-electron neutral or nearly neutral species.

I understand, thanks again for clarifying!

**Comment by mfgu** [comment]
the duplicated shells in configuration specification is now supported.
