### ISSUE TITLE
Ionization cross-section

### ISSUE THREAD

**Issue by atpchris** [flexible-atomic-code/fac#721]
Hi,
I am curious about the functionality of SetCIBorn, which I noticed is not mentioned in the manual. Could you please confirm if it is used to obtain the plane-wave Born ionization cross-section instead of the distorted-wave ionization cross-section?

Thank you for your time
Regards

**Comment by mfgu** [comment]
yes, that options is for plane-wave born approx, if the option for using distorted-wave born is first chosen. the default in FAC is using the faster method binary-encounter dipole approximation.
