### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by fujiisoup** [flexible-atomic-code/fac#94]
From #89, the automatic testings are failing.
@mfgu did you change something in the output?

I will update the testing code if necessary.

**Comment by mfgu** [comment]
yes. i changed the level configuration labels to include all occupied
shells. they are longer now. maybe write your reading routine to not depend
on the exact location of the columns. also you reading functions might be
helpful to others, so if you could put it under the pfac module, that would
be great.

**Comment by fujiisoup** [comment]
Thanks. OK. I will add the reading functions in PFAC and update the test codes, when I have a time.

**Comment by mfgu** [comment]
Hi Keisuke, i took some time to incorporate you read_* functions in pfac.rfac module. and fixed it for new level naming convention. the tests are passing in my local build. but still failed in the github PR.

**Comment by fujiisoup** [comment]
Thank you for incorporating these functions.
I will check it later.

**Comment by mfgu** [comment]
what i observed was that the data in the ref/ directory that the check script is comparing to is an old copy, even though i updated all data in the ref directory.
